name: test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - uses: github/codeql-action/init@v3
        with:
          config-file: ./.github/codeql/codeql-config.yml
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
